[package]
name = "houdini_bevy"
version = "0.1.0"

[env.macos.HOUDINI_PATH]
values = ["append:{root}:&"]

[env.linux.HOUDINI_PATH]
values = ["append:{root}"]

[env.windows.HOUDINI_PATH]
values = ["append:{root};&"]

[env.PYTHONPATH]
values = ["{root}/script"]
